name: LuckyBlock
main: LB\Main
author: [YOUSEEFXCRAFT,Hamooz001]
version: 1.1.3
api: [1.14.1, 2.0.0]

commands:
 lb:
  description: "Get LuckyBlock Plugin Information"
  permission: randomdropus.cmd
  default: true